from .english_to_french_generator import EnglishToFrenchGenerator
from .french_to_english_generator import FrenchToEnglishGenerator
from .french_synonym_generator import FrenchSynonymGenerator
from .french_antonym_generator import FrenchAntonymGenerator
from .section_prompt_generator import SectionPromptGenerator
