FROM python:3.8.7-slim-buster

WORKDIR /usr/src/api

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY requirements.txt /usr/src/api/requirements.txt
#RUN apk add --no-cache postgresql-libs
#RUN apk add --no-cache --virtual .build-deps gcc python3-dev musl-dev postgresql-dev
RUN pip install -r requirements.txt
#RUN apk --purge del .build-deps

COPY . /usr/src/api